baseURL: https://rekor.dev
languageCode: en-us
title: Project Rekor
theme: hugo-fresh
publishDir: "docs"
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

# Enable for syntax highlighting
pygmentsUseClasses: true
pygmentsCodeFences: true

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/rekor-logo.png
    link: /
  font:
    name: "Catamaran"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Project Rekor
    # Hero subtitle (optional)
    subtitle: Cryptographic, immutable, append only software release ledger tooling
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "/get_started/"
    # Hero image (from static/images/___)
    image: illustrations/rekor-logo-symbol-github.png
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: OpenAPI spec
    url: /
    # button: true
  - title: Get Started
    sublinks:
    - title: Rekor Client
      url: /get_started/client/
    - title: Rekor Server
      url: /get_started/server/
  - title: FAQ
    url: /faq/
  - title: Documentation
    sublinks:
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
  # section1:
  #   title: Great power comes
  #   subtitle: with great responsibility
  #   tiles:
  #   - title: App builder
  #     icon: mouse-globe
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Free trial
  #   - title: Cloud integration
  #     icon: laptop-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  #   - title: Add-ons & plugins
  #     icon: plug-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  section2:
    title: What can rekor provide
    subtitle: khjs
    features:
    - title: Production grade backend
      text: Rekor uses the certificate transparency project trillian as a cryptographic datastore. Trillian is production hardended software
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Mutliple Formats
      text: Rekor supports many existing formats such as SBOM, In-toto as well as the standard generic rekord type used by projects such as node.js, kernel
      icon: doc-sync
    - title: OpenAPI
      text: We have an openapi, you should use it.
      icon: mobile-feed
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  # section5: true
  # footer:
  #   # Logo (from /images/logos/___)
  #   logo: fresh-white-alt.svg
  #   # Social Media Title
  #   socialmediatitle: Follow Us
  #   # Social media links (GitHub, Twitter, etc.). All are optional.
  #   socialmedia:
  #   - link: https://github.com/lucperkins/github-fresh
  #     # Icons are from Font Awesome
  #     icon: github
  #   # - link: https://dribbble.com/#
  #   #   icon: dribbble
  #   # - link: https://facebook.com/#
  #   #   icon: facebook
  #   - link: https://twitter.com/lucperkins
  #     icon: twitter
  #   # - link: https://bitbucket.org/#
  #   #   icon: bitbucket
  #   bulmalogo: true
  #   quicklinks:
  #     column1:
  #       title: "Product"
  #       links:
  #       - text: Discover features
  #         link: /
  #       - text: Why choose our product?
  #         link: /
  #       - text: Compare features
  #         link: /
  #       - text: Our roadmap
  #         link: /
  #       - text: AGB
  #         link: /agb
  #     column2:
  #       title: "Docs"
  #       links:
  #       - text: Get started
  #         link: /
  #       - text: User guides
  #         link: /
  #       - text: Admin guide
  #         link: /
  #       - text: Developers
  #         link: /
  #     column3:
  #       title: "Blog"
  #       links:
  #       - text: Latest news
  #         link: /blog/first
  #       - text: Tech articles
  #         link: /blog/second
