baseURL: /
languageCode: en-us
title: sigstore
theme: hugo-fresh
publishDir: "docs"
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

# Enable for syntax highlighting
pygmentsUseClasses: true
pygmentsCodeFences: true
disableKinds: ["taxonomy", "taxonomyTerm", "section"]

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: "A non-profit, public good software signing & transparency service"
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/rekor-logo.png
    link: /
  font:
    name: "Catamaran"
    sizes: [400,600]
  hero:
    # Main hero title
    title: sigstore
    # Hero subtitle (optional)
    subtitle: A non-profit , public good software signing & transparency service
    # Button text
    buttontext: Learn More
    # Where the main hero button links to
    buttonlink: "/what_is_sigstore/"
    # Hero image (from static/images/___)
    image: illustrations/rekor-logo-symbol-github.png
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Community
    url: https://github.com/sigstore
    sublinks:
    - title: Rekor
      url: https://github.com/sigstore/rekor
    - title: Cosign
      url: https://github.com/sigstore/cosign
    - title: Fulcio
      url: https://github.com/sigstore/fulcio
    # button: true
  - title: Learn More
    url: "/what_is_sigstore/"
  - title: Slack
    url: https://join.slack.com/t/sigstore/shared_invite/zt-mhs55zh0-XmY3bcfWn4XEyMqUUutbUQ

#    - title: Fulcio WebPKI
#      url: /fulcio_webpki
#    - title: pkgsign Signing Client
#      url: /pksign_signing_client
#    - title: cosign Container Signing Client
#      url: /cosign_signing_client

  # section1:
  #   title: Current Users of Rekor
  #   subtitle: example projects
  #   tiles:
  #   - title: Acme Project
  #     icon: mouse-globe
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Find out more
  #   - title: Another Project
  #     icon: laptop-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Find out more
  #   - title: Add-ons & plugins
  #     icon: plug-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Find out more
  # # section2:
  #   title: What can rekor provide
  #   subtitle:
  #   features:
  #   - title: Production grade backend
  #     text: Rekor uses the certificate transparency project trillian as a cryptographic datastore. Trillian is production hardended software
  #     # Icon (from /images/illustrations/icons/___.svg)
  #     icon: laptop-cloud
  #   - title: Mutliple Formats
  #     text: Rekor supports many existing formats such as SBOM, In-toto as well as the standard generic rekord type used by projects such as node.js, kernel
  #     icon: doc-sync
  #   - title: OpenAPI
  #     text: We have an openapi, you should use it.
  #     icon: mobile-feed
  # section3:
  #   title: Integrate with Rekors API's
  #   subtitle: Learn how to use Rekor as part of your app eco-system
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Learn More
  #   buttonLink: "/get_started/"
  # section4:
  #   title: Current users of Rekor
  #   subtitle: User testimonials
  #   clients:
  #   - name: Irma Walters
  #     quote: As a community rekor has provided a transparent way of logging are software releases of the Acme Framework for our users.
  #     job: OSS project, Maintainer
  #     img: 1
  #   - name: John Bradley
  #     quote: We monitor rekor for activities that might suggest someone misusing our namespace or release signing keys.
  #     job: Developer, Super Security LTD
  #     img: 2
  #   - name: Gary Blackman
  #     quote: We run our own internal Rekor instance which has helped us meet the strict compilance needs of our customers.
  #     job: Cloud Engineer @ Big Cloud Inc
  #     img: 3
  # section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: lf.png
    # Social Media Title
